import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "on-surface": "#dee4de",
        "on-primary": "#003825",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-lowest": "#0a0f0c",
        "inverse-surface": "#dee4de",
        outline: "#333333",
        background: "#0a0a0a",
        "tertiary-container": "#dd706b",
        "on-background": "#dee4de",
        "primary-fixed": "#85f8c4",
        "on-primary-fixed": "#002114",
        "surface-variant": "#303632",
        "on-secondary-fixed-variant": "#474746",
        "on-primary-container": "#00311f",
        secondary: "#c8c6c5",
        "on-tertiary-fixed": "#410004",
        "error-container": "#93000a",
        "inverse-on-surface": "#2c322e",
        tertiary: "#ffb3ae",
        "on-secondary-container": "#b7b5b4",
        "inverse-primary": "#006c4a",
        "on-tertiary-fixed-variant": "#7f2928",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#601214",
        "secondary-container": "#474746",
        "on-error": "#690005",
        "on-secondary": "#313030",
        primary: "#68dba9",
        "on-surface-variant": "#bccac0",
        "primary-fixed-dim": "#68dba9",
        "surface-dim": "#0f1511",
        "secondary-fixed": "#e5e2e1",
        "outline-variant": "#3d4a42",
        "surface-bright": "#343b37",
        "on-primary-fixed-variant": "#005137",
        "tertiary-fixed": "#ffdad7",
        "primary-container": "#25a475",
        "tertiary-fixed-dim": "#ffb3ae",
        "surface-container-high": "#252b28",
        "surface-container-low": "#171d19",
        "surface-tint": "#68dba9",
        "surface-container": "#1b211d",
        "on-tertiary-container": "#570b0e",
        surface: "#1a1a1a",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-highest": "#303632",
        nutri: {
          slate: {
            50: "#f8fafc",
            100: "#f1f5f9",
            200: "#e2e8f0",
            300: "#cbd5e1",
            400: "#94a3b8",
            500: "#64748b",
            600: "#475569",
            700: "#334155",
            800: "#1e293b",
            900: "#0f172a",
            950: "#020617",
          },
          emerald: {
            soft: "#d1fae5",
            muted: "#6ee7b7",
            DEFAULT: "#68dba9",
            deep: "#25a475",
            ink: "#064e3b",
          },
        },
        light: {
          surface: "#f5fbf5",
          onSurface: "#171d19",
          outline: "#6d7a72",
          primary: "#006948",
          surfaceContainer: "#e9efe9",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        xl: "40px",
        sm: "8px",
        xs: "4px",
        unit: "4px",
        lg: "24px",
        "container-padding": "20px",
        gutter: "12px",
        "scale-8": "32px",
        "sidebar-offset": "32px",
        "scale-7": "30px",
        "page-margin": "32px",
      },
      fontFamily: {
        h2: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        "label-caps": ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        h1: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        "mono-data": ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        h3: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        "body-sm": ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        "label-sm": ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        "body-bold": ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        "body-base": ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        "display-lg": ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        sans: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        display: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-bold": ["14px", { lineHeight: "20.0004px", fontWeight: "600" }],
        "body-base": ["14px", { lineHeight: "20.0004px", fontWeight: "400" }],
        "display-lg": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
      },
      boxShadow: {
        float: "0 4px 24px rgba(0,0,0,0.4)",
        nav: "0 2px 8px rgba(0,0,0,0.2)",
      },
    },
  },
  plugins: [],
};

export default config;
